apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:13.4-alpine3.14
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: testdb
            - name: POSTGRES_USER
              value: testuser
            - name: POSTGRES_PASSWORD
              value: testpassword
          volumeMounts:
            - name: pg-persistent-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: pg-persistent-storage
          persistentVolumeClaim:
            claimName: pg-pvc-ssd
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
