---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pg-pvc-ssd
spec:
  storageClassName: "csi-ceph-ssd-dp1"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
